# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='prefield creations', max_length=255),
            preserve_default=False,
        ),
    ]
